github:
  repo: 'cloudy-astrophysics/bug-tracker-migration-test'  

users:
  'gary / robin': CloudyLex
  gary: CloudyLex
  rjrw: rjrw
  will: will-henney
  mchatzikos: mchatzikos
  fguzman: fguzmanful
  # nicholas: MISSING
  # wangye0206: MISSING
  # dquan: MISSING
  # matt: MISSING
  # peter: MISSING
  # 'Peter, van, Hoof, <p.vanhoof@oma.be>': MISSING
  # rporter: MISSING
  # Ryan: MISSING
  # 'rporter@pa.uky.edu' MISSING
  # nobody: MISSING
  # somebody: MISSING
  # anonymous: MISSING
  
  
