github:
  repo: 'cloudy-astrophysics/bug-tracker-migration-test'  

users:
  'gary / robin': CloudyLex
  gary: CloudyLex
  rjrw: rjrw
  will: will-henney
  mchatzikos: mchatzikos
  fguzman: fguzmanful
  # nicholas: MISSING
  # wangye0206: MISSING
  # dquan: MISSING
  # matt: MISSING
  peter: peter-van-hoof-noaccount
  'Peter, van, Hoof, <p.vanhoof@oma.be>': peter-van-hoof-noaccount
  rporter: ryan-porter-noaccount
  Ryan: ryan-porter-noaccount
  'rporter@pa.uky.edu': ryan-porter-noaccount
  # nobody: MISSING
  # somebody: MISSING
  # anonymous: MISSING
  
  
